version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package CAPABILITY_AUTO_EXPAND --template-file samTemplate.yaml --s3-bucket demo-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
