AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Setting thermal-events
Globals:
  Function:
    Runtime: !Ref PythonRuntime
    MemorySize: 256
    Timeout: 15
    CodeUri:
      Bucket: !Ref LambdaCodeS3Bucket
      Key: !Ref LambdaCodeS3Key

Resources:

  AutoScalingDynamoDBRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: ScalingDynamoDB
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:DescribeTable'
                  - 'dynamodb:UpdateTable'
                  - 'cloudwatch:PutMetricAlarm'
                  - 'cloudwatch:DescribeAlarms'
                  - 'cloudwatch:GetMetricStatistics'
                  - 'cloudwatch:SetAlarmState'
                  - 'cloudwatch:DeleteAlarms'
                Resource: '*'

  EventsConfigTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Join
        - ''
        - - EventsConfig-
          - !Ref RealmName
      AttributeDefinitions:
        - AttributeName: EventType
          AttributeType: S
      KeySchema:
        - AttributeName: EventType
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'

Parameters:
  InstanceName:
    Default: dev
    Description: The name of this instance
    Type: String
    MinLength: '2'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9][a-zA-Z0-9]*'
    ConstraintDescription: >-
      must begin with a letter, at least two characters, and contain only alphanumeric characters.
  Version:
    Description: stack version.
    Type: String
  LambdaCodeS3Bucket:
    Description: The S3 Bucket of lambda code
    Type: String
  LambdaCodeS3Key:
    Description: The S3 Key of lambda code
    Type: String
  RealmName:
    Description: target data realm.
    Type: String
  PythonRuntime:
    Description: Python runtime
    Type: String
    Default: python3.8
  CloudFrontKeyPairID:
    Description: CloudFront Key Pair ID
    Type: String
  CloudFrontKeyPairBucket:
    Description: CloudFront Key Pair Bucket
    Type: String
  CloudFrontKeyPairFileKey:
    Description: CloudFront Key Pair File Key
    Type: String
