events_build_steps: &events_build_steps
  steps:
    - run: echo "Triggering branch $TRIGGER_BRANCH"
    - run: |
        echo "export IS_PREVIEW=$([[ $TRIGGER_BRANCH == 'preview' ]] && echo 'true' || echo '')" >> $BASH_ENV
    - run: echo "Is Preview? $IS_PREVIEW"
    - checkout
    - attach_workspace:
        at: ~/LambdaCDDemo
    - persist_to_workspace:
        root: ~/LambdaCDDemo
        paths:
          - events

test_dev_stack_deploy_steps: &test_dev_stack_deploy_steps
  steps:
    - run: |
        # these are all provided by circleci project settings > environment variables
        echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
        echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV

    - checkout
    - attach_workspace:
        at: ~/LambdaCDDemo
    - run:
        name: Deploy Stack
        command: sh ./cloudformation/deploy.sh

# Does this even still work?
# notify:
#   webhooks:
#     - url: https://idobata.io/hook/circle_ci/58352f43-a98c-4acc-8de4-45e81b6a5566
version: 2.1
jobs:
  events_build:
    working_directory: ~/LambdaCDDemo
    environment:
      TRIGGER_BRANCH: << pipeline.git.branch >>
    docker:
      # Not Sure if API build needs this image in order to run ffmpeg/ffprobe in unit tests TODO POC
      - image: alpine:3.7
    <<: *events_build_steps
  event-deploy-test-dev:
    working_directory: ~/LambdaCDDemo
    docker:
      - image: alpine:3.7
        environment:
          AWS_REGION: ap-south-1
          PARAMETER_LOCAL_FILE_PATH: config/environment/test-dev.yaml
          STACK_FLAG: --with-events
    <<: *test_dev_stack_deploy_steps
  build:
    docker:
      - image: circleci/node:12
    steps:
      - run: echo "All build steps completed."

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # pub deploy jobs
      - events_build
      - event-deploy-test-dev
      - build:
          requires:
            - events_build
