# 1. We must use version 2.1 to enable orbs.
version: 2.1

# 2. Bring in the current version of the aws-serverless orb
orbs:
  # 3. We name our imported orb “sam”
  sam: circleci/aws-sam-serverless@2.0.0

jobs:
  test_my_api:
    executor: sam/default
    steps:
      - run: echo "Run your tests here"

workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy-staging
          stack-name: staging-stack
          template: template.yml
      - test_my_api:
          requires:
            - deploy-staging
      - sam/deploy:
          name: deploy-production
          requires:
            - test_my_api
          stack-name: production-stack
          template: template.yml
