events_build_steps: &events_build_steps
  steps:
    - run: echo "Triggering branch $TRIGGER_BRANCH"
    - run: |
        echo "export IS_PREVIEW=$([[ $TRIGGER_BRANCH == 'preview' ]] && echo 'true' || echo '')" >> $BASH_ENV
    - run: echo "Is Preview? $IS_PREVIEW"
    - checkout
    - attach_workspace:
        at: ~/LambdaCDDemo
    - persist_to_workspace:
        root: ~/LambdaCDDemo
        paths:
          - events

test_dev_stack_deploy_steps: &test_dev_stack_deploy_steps
  steps:
    - run: |
        # these are all provided by circleci project settings > environment variables
        echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
        echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV

    - checkout
    - attach_workspace:
        at: ~/LambdaCDDemo
    - run:
        name: Deploy Stack
        command: ./deploy.sh --parameter-local-file-path $PARAMETER_LOCAL_FILE_PATH $STACK_FLAG

# Does this even still work?
# notify:
#   webhooks:
#     - url: https://idobata.io/hook/circle_ci/58352f43-a98c-4acc-8de4-45e81b6a5566
version: 2.1
jobs:
  event-deploy-test-dev:
    working_directory: ~/LambdaCDDemo
    docker:
      - image: futurestandard/scorer-cloud-deploy:1.2
        environment:
          AWS_REGION: ap-south-1
          PARAMETER_LOCAL_FILE_PATH: config/environment/test-dev.yaml
          STACK_FLAG: --with-events
    <<: *test_dev_stack_deploy_steps

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # pub deploy jobs
      - event-deploy-test-dev
