# 1. We must use version 2.1 to enable orbs.
version: 2.1

# 2. Bring in the current version of the aws-serverless orb
orbs:
  # 3. We name our imported orb “sam”
  sam: circleci/aws-sam-serverless@2.0.0

jobs:
  test_my_api:
    executor: sam/default
    steps:
      - run: echo "Run your tests here"

workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy-storage
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-no5vp6ouattx
          stack-name: storage-events
          template: storage/template.yaml

      - sam/deploy:
          name: deploy-upload-image
          requires:
            - deploy-storage
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-no5vp6ouattx
          stack-name: upload-image
          template: upload_image/template.yaml

      - sam/deploy:
          name: deploy-event-api
          requires:
            - deploy-storage
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-no5vp6ouattx
          stack-name: fti-events
          template: events/cloudformation/template.yaml
