RealmName: dev
InstanceName: dev
ScorerApiVersion: 1-41-0
StorageEventFunctionVersion: 1-14
AuthenticationEventFunctionVersion: 1-2
ClusterEventFunctionVersion: 1-0
ScorerAdminFunctionVersion: 1-0
S3BucketNamePrefix: future-standard.scorer
AWSRegion: ap-northeast-1
CodeUploadBucket: future-standard.cloudformation
HostedZoneId: Z3LFVVJYWXNSY
LicenseUrl: https://license-dev.scorer.jp
AllowedOrigins:
  - https://staging.scorer.jp
  - https://staging.rc.scorer.jp
  - https://staging-qa.scorer.jp
  - http://localhost:3000
  - http://localhost:4000
  - http://smc-prs.s3-website-ap-northeast-1.amazonaws.com
CloudFrontKeyPair:
  ID: APKAIULBXX6NBDLI4LXA
  Bucket: future-standard.keys
  FileKey: cloudfront/pk-APKAIULBXX6NBDLI4LXA.pem.txt
Cognito:
  DatasetName: ScorerStarter
Lambda:
  DefaultNodeRuntime: nodejs12.x
  EdgeNodeRuntime: nodejs10.x
S3Retention:
  Synthesized:
    DefaultRetention: "031"
    Tags:
      Texts:
        "031":
          ID: S31-IA0-G0-V7-E31
          ExpirationInDays: 31
          NoncurrentVersionExpirationInDays: 7
UserStorage:
  StorageLimitInMB: 1000
UserDataRetention:
  BillingRate: 0.2
  DefaultRetention: "007"
  Retentions:
    "001":
      TagValue: D001
      ExpirationInDays: 1
      NoncurrentVersionExpirationInDays: 1
    "003":
      TagValue: D003
      ExpirationInDays: 3
      NoncurrentVersionExpirationInDays: 1
    "007":
      TagValue: D007
      ExpirationInDays: 7
      NoncurrentVersionExpirationInDays: 1
    "014":
      TagValue: D014
      ExpirationInDays: 14
      NoncurrentVersionExpirationInDays: 7
    "030":
      TagValue: D030
      ExpirationInDays: 30
      NoncurrentVersionExpirationInDays: 7
    "060":
      TagValue: D060
      ExpirationInDays: 60
      NoncurrentVersionExpirationInDays: 7
    "090":
      TagValue: D090
      ExpirationInDays: 90
      NoncurrentVersionExpirationInDays: 7
    "180":
      TagValue: D180
      ExpirationInDays: 180
      NoncurrentVersionExpirationInDays: 7
    "365":
      TagValue: D365
      ExpirationInDays: 365
      NoncurrentVersionExpirationInDays: 7
VPNSettings:
  URL:  https://kksegalevf.execute-api.ap-northeast-1.amazonaws.com/v1
  ClusterId: scorervpn-staging
  StartIP: 192.168.30.2
  EndIP: 192.168.30.200
InternalApi:
  DomainName: internal-api-dev.scorer.jp
  UsagePlanId: bpsv3n
  ACMCertificateArn: arn:aws:acm:us-east-1:753232328716:certificate/5248de62-bd04-4413-9e50-77782f690d17
MediaServer:
  HostName: https://cr3t5rqzxf.execute-api.ap-northeast-1.amazonaws.com/prod
  IdentityPoolID: ap-northeast-1:d1968466-43d9-4112-89e4-f131b8cd3e9b
VPC:
  Cidr: 10.100.0.0/16
UserStorageSync:
  Subnets:
    - AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.100.21.0/24
    - AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.100.22.0/24
    - AvailabilityZone: ap-northeast-1d
      CidrBlock: 10.100.23.0/24
  Parallel: 1
  EC2InstanceType: t3.small
  ClusterName: default
  AllowedExportRegions:
    - ap-northeast-1
  AMIID: ami-03a1a0269736ff2a1
LogExtractor:
  Subnets:
    - AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.100.31.0/24
    - AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.100.32.0/24
    - AvailabilityZone: ap-northeast-1d
      CidrBlock: 10.100.33.0/24
  Parallel: 1
  EC2InstanceType: r5.large
  ClusterName: default
  AMIID: ami-0c83c63871d3344ab
Download:
  Subnets:
    - AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.100.41.0/24
    - AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.100.42.0/24
    - AvailabilityZone: ap-northeast-1d
      CidrBlock: 10.100.43.0/24
  Parallel: 1
  EC2InstanceType: c5.large
  ClusterName: default
  AMIID: ami-044a86b63a3f1e356
  ExpirationInDays: 7
Dax:
  ClusterName: default
  NodeType: dax.t2.small
  NodeCount: 2
  Subnets:
    - AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.100.101.0/24
    - AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.100.102.0/24
  Endpoint: dax-cluster-dev.scorer.jp
PublicApi:
  Version: v1
  VersionPrefix: 1-7
  EdgeCodeUploadBucket: future-standard.cloudformation.us
  DomainName: api-dev.scorer.jp
  ACMCertificateArn: arn:aws:acm:us-east-1:753232328716:certificate/31f83812-51b3-48c7-afea-4b92bf60d5e4
  LambdaVersionUpdate: true
  PostVcaJob:
    OnDemand:
      PeriodUpperLimitHours: 12
  Document:
    PostmanCollectionId: 89169d64-288c-4c05-8407-3998451f668c
    Title: "[dev] SCORER API"
    Version: "1.3"
Stripe:
  TaxRateID: txr_1FU07QKL8UDw1bVxUKT2ONdj
  PublicKey: pk_test_MXzwe4LrPV54N6T5Bi8ESfAb
DeviceMonitoring:
  SESRegion: eu-west-1
  SenderEmailAddress: no-reply@futurestandard.co.jp
ScorerUI:
  DomainName: staging.scorer.jp
  BucketName: future-standard.scorer.web.dev.staging.scorer.jp
  ACMCertificateArn: arn:aws:acm:us-east-1:753232328716:certificate/31f83812-51b3-48c7-afea-4b92bf60d5e4
  APIDocumentationURL: https://api-docs.scorer.dev
  OnDemandMax: 12
  BugherdKey: mmmpnctt5qwjsg6tvq0ppg
  Downloads: true
  CreditCard: true
  ShowSignup: true
  ExportServiceFolders: true
  SentryDSN: https://9b7c5a8086014556b8f1ed6261b5124c@sentry.io/1874685
  IceServers: '[{"urls": "stun:stun.l.google.com:19302"},{"urls": "turn:18.179.119.83:443?transport=tcp","credential": "bitskey@123L","username":"bitskey"}]'
ScorerAdmin:
  Hostname: admin-dev.scorer.jp
  BucketName: future-standard.scorer.admin.ui.dev
  ACMCertificateArn: arn:aws:acm:us-east-1:753232328716:certificate/31f83812-51b3-48c7-afea-4b92bf60d5e4
# optional
ExistingScorer: true
Slack:
  Deploy:
    - Url: https://hooks.slack.com/services/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
      Channel: "#scorer_dev_logs"
    - Url: https://hooks.slack.com/services/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
      Channel: "#scorer_dev"
  Stripe:
    Url: https://hooks.slack.com/services/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
    Channel: "#dev_notify"
  SenseVideoTrial:
    Url: https://hooks.slack.com/services/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
    Channel: "#dev_notify"
  LogExtractor:
    Url: https://hooks.slack.com/services/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
    Channel: "#scorer_dev"
