RealmName: pub
InstanceName: pub
ScorerApiVersion: 1-41-0
StorageEventFunctionVersion: 1-14
AuthenticationEventFunctionVersion: 1-2
ClusterEventFunctionVersion: 1-0
ScorerAdminFunctionVersion: 1-0
S3BucketNamePrefix: future-standard.scorer
AWSRegion: ap-northeast-1
CodeUploadBucket: future-standard.cloudformation
HostedZoneId: Z3LFVVJYWXNSY
LicenseUrl: https://license.scorer.jp
AllowedOrigins:
  - https://console.scorer.jp
  - https://smoketest.scorer.jp
CloudFrontKeyPair:
  ID: APKAIULBXX6NBDLI4LXA
  Bucket: future-standard.keys
  FileKey: cloudfront/pk-APKAIULBXX6NBDLI4LXA.pem.txt
Cognito:
  DatasetName: ScorerStarter
Lambda:
  DefaultNodeRuntime: nodejs12.x
  EdgeNodeRuntime: nodejs10.x
S3Retention:
  Synthesized:
    DefaultRetention: "031"
    Tags:
      Texts:
        "031":
          ID: S31-IA0-G0-V7-E31
          ExpirationInDays: 31
          NoncurrentVersionExpirationInDays: 7
UserStorage:
  StorageLimitInMB: 1000
UserDataRetention:
  BillingRate: 0.2
  DefaultRetention: "007"
  Retentions:
    "001":
      TagValue: D001
      ExpirationInDays: 1
      NoncurrentVersionExpirationInDays: 1
    "003":
      TagValue: D003
      ExpirationInDays: 3
      NoncurrentVersionExpirationInDays: 1
    "007":
      TagValue: D007
      ExpirationInDays: 7
      NoncurrentVersionExpirationInDays: 1
    "014":
      TagValue: D014
      ExpirationInDays: 14
      NoncurrentVersionExpirationInDays: 7
    "030":
      TagValue: D030
      ExpirationInDays: 30
      NoncurrentVersionExpirationInDays: 7
    "060":
      TagValue: D060
      ExpirationInDays: 60
      NoncurrentVersionExpirationInDays: 7
    "090":
      TagValue: D090
      ExpirationInDays: 90
      NoncurrentVersionExpirationInDays: 7
    "180":
      TagValue: D180
      ExpirationInDays: 180
      NoncurrentVersionExpirationInDays: 7
    "365":
      TagValue: D365
      ExpirationInDays: 365
      NoncurrentVersionExpirationInDays: 7
VPNSettings:
  URL: https://zblxw1bvr9.execute-api.ap-northeast-1.amazonaws.com/auth_api
  ClusterId: vpn-prod
  StartIP: 192.168.30.2
  EndIP: 192.168.30.200
InternalApi:
  DomainName: internal-api.scorer.jp
  UsagePlanId: b2o6g1
  ACMCertificateArn: arn:aws:acm:us-east-1:753232328716:certificate/fca08c35-74e0-4ee6-8437-795fdacc2a91
MediaServer:
  HostName: https://cr3t5rqzxf.execute-api.ap-northeast-1.amazonaws.com/prod
  IdentityPoolID: ap-northeast-1:d1968466-43d9-4112-89e4-f131b8cd3e9b
VPC:
  Cidr: 10.0.0.0/16
UserStorageSync:
  Subnets:
    - AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.21.0/24
    - AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.22.0/24
    - AvailabilityZone: ap-northeast-1d
      CidrBlock: 10.0.23.0/24
  Parallel: 1
  EC2InstanceType: r5.xlarge
  ClusterName: default
  AllowedExportRegions:
    - ap-northeast-1
  AMIID: ami-03a1a0269736ff2a1
LogExtractor:
  Subnets:
    - AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.31.0/24
    - AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.32.0/24
    - AvailabilityZone: ap-northeast-1d
      CidrBlock: 10.0.33.0/24
  Parallel: 1
  EC2InstanceType: r5.large
  ClusterName: default
  RootVolumeSize: 100
  AMIID: ami-05d0364109d1e40d9
Download:
  Subnets:
    - AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.41.0/24
    - AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.42.0/24
    - AvailabilityZone: ap-northeast-1d
      CidrBlock: 10.0.43.0/24
  Parallel: 1
  EC2InstanceType: c5.large
  ClusterName: default
  AMIID: ami-044a86b63a3f1e356
  ExpirationInDays: 7
Dax:
  ClusterName: default
  NodeType: dax.t2.small
  NodeCount: 2
  Subnets:
    - AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.101.0/24
    - AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.102.0/24
  Endpoint: dax-cluster-pub.scorer.jp
PublicApi:
  Version: v1
  VersionPrefix: 1-7
  EdgeCodeUploadBucket: future-standard.cloudformation.us
  DomainName: api.scorer.jp
  ACMCertificateArn: arn:aws:acm:us-east-1:753232328716:certificate/dead8908-c9a8-497d-bd2f-3168275a5873
  LambdaVersionUpdate: true
  PostVcaJob:
    OnDemand:
      PeriodUpperLimitHours: 4
  Document:
    PostmanCollectionId: fda94891-5df2-45c9-b37c-401bbf99933c
    Title: "SCORER API"
    Version: "1.3"
Stripe:
  TaxRateID: txr_1FU7j7KL8UDw1bVxEZM4OIuK
  PublicKey: pk_live_1bEQa0Ojfk810hbzxSr98sgj
DeviceMonitoring:
  SESRegion: eu-west-1
  SenderEmailAddress: no-reply@futurestandard.co.jp
ScorerUI:
  DomainName: console.scorer.jp
  BucketName: future-standard.scorer.web.pub.console.scorer.jp
  ACMCertificateArn: arn:aws:acm:us-east-1:753232328716:certificate/31f83812-51b3-48c7-afea-4b92bf60d5e4
  APIDocumentationURL: https://api-docs.scorer.dev
  OnDemandMax: 4
  BugherdKey: mmmpnctt5qwjsg6tvq0ppg
  Downloads: true
  CreditCard: true
  ShowSignup: true
  ExportServiceFolders: false
  SentryDSN: https://9b7c5a8086014556b8f1ed6261b5124c@sentry.io/1874685
  IceServers: '[{"urls": "stun:stun.l.google.com:19302"},{"urls": "turn:18.179.119.83:443?transport=tcp","credential": "bitskey@123L","username":"bitskey"}]'
ScorerAdmin:
  Hostname: admin-console.scorer.jp
  BucketName: future-standard.scorer.admin.ui.pub
  ACMCertificateArn: arn:aws:acm:us-east-1:753232328716:certificate/31f83812-51b3-48c7-afea-4b92bf60d5e4
# optional
ExistingScorer: true
Slack:
  Deploy:
    - Url: https://hooks.slack.com/services/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
      Channel: "#scorer_dev_logs"
    - Url: https://hooks.slack.com/services/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
      Channel: "#scorer_dev"
  Stripe:
    Url: https://hooks.slack.com/services/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
    Channel: "#scorer_billing"
  SnsNotification:
    Url: https://hooks.slack.com/services/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
    Channel: "#trial_site"
  LogExtractor:
    Url: https://hooks.slack.com/services/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
    Channel: "#scorer_dev"
